### ISSUE TITLE
Could not unregister reminder in HistoryQueueProcessor.

### ISSUE THREAD

**Issue by ElanHasson** [web-scheduler/web-scheduler#146]
### Describe the bug

```
[16:43:06 ERR] Could not unregister reminder <IOrleansReminder: GrainRef=GrainReference:*grn/WebScheduler.Grains.Scheduler.ScheduledTaskGrain/0+047bdf1e-67ae-4e40-ae38-7219f4917de5-0xAFE50544 ReminderName=HistoryQueueProcessor ETag=0> from the reminder table, due to tag mismatch. You can retry.
[16:43:06 ERR] Could not deliver reminder tick for [HistoryQueueProcessor, GrainReference:*grn/WebScheduler.Grains.Scheduler.ScheduledTaskGrain/0+047bdf1e-67ae-4e40-ae38-7219f4917de5-0xAFE50544, 00:01:00, 2022-07-23 12:46:06.746 GMT, 1, 99480, Ticking], next 7/23/2022 4:44:06 PM.
Orleans.Runtime.ReminderException: Could not unregister reminder <IOrleansReminder: GrainRef=GrainReference:*grn/WebScheduler.Grains.Scheduler.ScheduledTaskGrain/0+047bdf1e-67ae-4e40-ae38-7219f4917de5-0xAFE50544 ReminderName=HistoryQueueProcessor ETag=0> from the reminder table, due to tag mismatch. You can retry.
   at Orleans.Runtime.ReminderService.LocalReminderService.UnregisterReminder(IGrainReminder reminder) in /_/src/Orleans.Runtime/ReminderService/LocalReminderService.cs:line 153
   at Orleans.OrleansCodeGenReminderServiceMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request) in /_/src/Orleans.Core/obj/Release/net6.0/Orleans.Core.orleans.g.cs:line 5083
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
   at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
   at WebScheduler.Server.Interceptors.TenantValidationInterceptor.Invoke(IIncomingGrainCallContext context) in /src/Source/WebScheduler.Server/Interceptors/TenantValidationInterceptor.cs:line 59
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
   at WebScheduler.Grains.Scheduler.ScheduledTaskGrain.ProcessHistoryQueueAsync(Int32 batchSize) in /src/Source/WebScheduler.Grains/Scheduler/ScheduledTaskGrain.cs:line 355
   at WebScheduler.Grains.Scheduler.ScheduledTaskGrain.ReceiveReminder(String reminderName, TickStatus status) in /src/Source/WebScheduler.Grains/Scheduler/ScheduledTaskGrain.cs:line 339
   at Orleans.OrleansCodeGenRemindableMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request) in /_/src/Orleans.Core/obj/Release/net6.0/Orleans.Core.orleans.g.cs:line 5215
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
   at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
   at WebScheduler.Server.Interceptors.TenantValidationInterceptor.Invoke(IIncomingGrainCallContext context) in /src/Source/WebScheduler.Server/Interceptors/TenantValidationInterceptor.cs:line 59
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in /_/src/Orleans.Runtime/Core/GrainMethodInvoker.cs:line 104
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in /_/src/Orleans.Runtime/Core/InsideRuntimeClient.cs:line 469
   at Orleans.Runtime.ReminderService.LocalReminderService.LocalReminderData.OnTimerTick() in /_/src/Orleans.Runtime/ReminderService/LocalReminderService.cs:line 631
[16:43:07 ERR] Error executing HttpTrigger for 5755f5ee-b97e-be89-7c9b-3c8d74abb6da.
```

### Steps to reproduce

System was under heavy load at the time and got a high error rate.

### Expected behaviour

Reminder should be able to be unregistered.

**Comment by ElanHasson** [comment]
It seems the handle to our `HistoryQueueProcessor` reminder is stale (etag =0), so must `GetReminder()` it again.
